### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/hr-expense#131]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] hr_expense_advance_clearing - By @Saran440 - #203
- [x] hr_expense_cancel - By @stefan-tecnativa - #187
- [x] hr_expense_invoice - By @victoralmau - #220
- [x] hr_expense_journal - By @Saran440 - #251
- [x] hr_expense_payment - By @AungKoKoLin1997 - #155
- [ ] hr_expense_petty_cash - By @Saran440 - #228
- [x] hr_expense_sequence - By @Saran440 - #213
- [x] hr_expense_tier_validation - By @AnutToc - #209
- [ ] sale_expense_manual_reinvoice - By @MarwanBHL - #296

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by ray-odoo** [comment]
Anyone working on hr_expense_portal for 16.0?

**Comment by pedrobaeza** [comment]
@ray-odoo it doesn't seem so for now.

**Comment by ray-odoo** [comment]
Ok. It installs fine and /my/expenses works fine. It just doesn't show the Expenses link on the main portal page so if I can work out why I will report back.

**Comment by discapacidad5** [comment]
Anyone working on hr_expense_petty_cash for 16.0?

**Comment by em230418** [comment]
> Ok. It installs fine and /my/expenses works fine. It just doesn't show the Expenses link on the main portal page so if I can work out why I will report back.

Hi, @ray-odoo! Have you resolved this issue?

**Comment by francescapenso** [comment]
> Anyone working on hr_expense_petty_cash for 16.0?

i'm also interested

**Comment by ray-odoo** [comment]
@francescapenso no, but I will report back if it is resolved, as there is still a chance it will be used in one of my projects

**Comment by francescapenso** [comment]
@ray-odoo you mean you're thinking about porting?

**Comment by ray-odoo** [comment]
@francescapenso there is still a discussion about porting but no decision has been made yet

**Comment by em230418** [comment]
> Anyone working on hr_expense_portal for 16.0?

Hi again @ray-odoo!
I am working on it https://github.com/OCA/hr-expense/pull/195
Currently PR fails on test from other module.

**Comment by gjlong68** [comment]
Anyone working on HR Expense Advance Clearing for 16.0?

**Comment by ray-odoo** [comment]
@em230418 looks good so far - the Expenses link on the main portal page is working!  It is missing Filter, Group by and Search but the rest of it functions well.  The font size is larger than the Timesheets list. 

cc @francescapenso

**Comment by Saran440** [comment]
@gjlong68 Hi, hr_expense_advance_clearing version 16 is here -> https://github.com/OCA/hr-expense/pull/203
Can you help review, please?

**Comment by gjlong68** [comment]
I can




郭Sir
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OCA/hr-expense"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月18日(星期一) 中午1:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OCA/hr-expense] Migration to version 16.0 (Issue #131)





 
@gjlong68 Hi, hr_expense_advance_clearing version 16 is here -&gt; #203
 Can you help review, please?

**Comment by yboujraf** [comment]
@Saran440 are you porting as well hr_expense_journal as done for 15.0 few weeks ago ?

Best Regards

**Comment by gjlong68** [comment]
Anyone working on HR Expense Advance Invoice 16.0?

**Comment by gjlong68** [comment]
Anyone working on HR Expense Invoice 16.0?

**Comment by MarwanBHL** [comment]
sale_expense_manual_reinvoice #296
